---
# vim: set ft=ansible:
#
#   This role verifies the atomic run command.  This role requires no other
#   containers to be running besides the one being run.
#
#   Commands:
#   - atomic run
#
- name: Fail if container is undefined
  fail:
    msg="No container specified"
  when: container is undefined

- name: atomic run {{ container }}
  command: atomic run {{ container }}

- name: Verify container is running
  command: docker ps -a
  register: dps

- name: Fail if container is not running
  fail:
    msg="Container is not Up or Created in docker ps -a output"
  when: (dps.stdout.find("Up") == -1 and dps.stdout.find("Created") == -1)
